app:
  theme: "default"
  verify_version: true
  emoji: false
  terminal_colorful: false
  run_time_app: 1
  monitor_to_use: 1

time_intervals:
  active_seed: 20
  sell_crops: 20

threshold:
  default: 0.8
  crops_item: 0.75
  buy_seeds: 0.95
  sell_seeds: 0.99
  button_buy_seeds: 0.97
  button_sell_seeds: 0.97
  menu_buttons: 0.99

services:
  telegram: false
  
log:
  save_to_file: false
  console: false
  show_print: false
